Update learn

diff --git a/scripts/firstrun/learn b/scripts/firstrun/learn
--- a/scripts/firstrun/learn
+++ b/scripts/firstrun/learn
@@ -16,12 +16,14 @@ function SetupWindow {
   elif [ $button -eq 5 ];then
     step=$((step+1))
     yad --separator='\n' --title="$AppName Part:$step" --image="/home/pi/CryApp/icon.png" --center --width='300' --height='300' --text-align="center" --text="Click the '+' button to add a task or reminder." --window-icon="${DIRECTORY}/icons/logo.png" --button=Exit!"${DIRECTORY}/icons/exit.png"!'Exit':6 --button='Next'!"${DIRECTORY}/icons/forward.png"!'Continue.':7
-  elif [ $button -eq 6 ];then
-    step=$((step+1))
-  elif [ $button -eq 7 ];then
-    step=$((step+1))
-    yad --separator='\n' --title="$AppName Setup Step:$step" --center --width='300' --height='300' --text-align="center" --text="Welcome to the $AppName Setup wizard!" --window-icon="${DIRECTORY}/icons/logo.png" --button=Cancel!"${DIRECTORY}/icons/exit.png"!'Exit':2 --button='Next'!"${DIRECTORY}/icons/forward.png"!'Continue.':3
+    button=$? #get exit code to determine which button was pressed.
+    if [ $button -eq 6 ];then
+      echo "True" > $DIRECTORY/data/info/opd
+    elif [ $button -eq 7 ];then
+      step=$((step+1))
+      echo "True" > $DIRECTORY/data/info/opd
   elif [ $button -eq 252 ];then
+    echo "True" > $DIRECTORY/data/info/opd
     echo "User exited"
   else
     error "Unkown button input recived: $button"
