Update gui

diff --git a/scripts/gui b/scripts/gui
--- a/scripts/gui
+++ b/scripts/gui
@@ -17,11 +17,8 @@ if [ $Used == "True" ]; then
           items+=( "None" "None" )
         fi
     done < <(sort -t'|' -k2 $DIRECTORY/Tasks/Tasks.txt)
-    OPTION="$(yad --separator='\n' --title="$AppName" --window-icon="${DIRECTORY}/icons/logo.png" --center --width='300' --height='300' --text-align="center" --text="Welcome to $AppName! \nWhat would you like to do?" --button="Add new Task/Reminder"!"${DIRECTORY}/icons/install.png"!'Create a new Task/Reminder':2 --button="Delete Task/Reminder"!"${DIRECTORY}/icons/uninstall.png"!'Delete Task/Reminder':3 --button="Edit a Task/Reminder"!"${DIRECTORY}/icons/edit.png"!'Edit a Task/Reminder':4 --list --column=Task/Reminder "${items[0]}" --column=Date "${items[1]}")"
-    if [ -z "$OPTION" ]; then
-      yad --separator='\n' --title="Error" --window-icon="${DIRECTORY}/icons/courupted.png" --center --width='300' --height='300' --text-align="center" --text="Error! \nYou didn't select a Task/Reminder! Please select a Task/Reminder and try again." --button="Ok"!"${DIRECTORY}/icons/back.png"!'Go back and select Task/Reminder to delete.':5
-      bash $DIRECTORY/main "gui"
-    elif [ "$button" -eq 252 ];then
+    OPTION="$(yad --separator='\n' --title="$AppName" --window-icon="${DIRECTORY}/icons/logo.png" --center --width='300' --height='300' --text-align="center" --text="Welcome to $AppName! \nWhat would you like to do?" --button="Add new Task/Reminder"!"${DIRECTORY}/icons/install.png"!'Create a new Task/Reminder':2 --button="Delete Task/Reminder"!"${DIRECTORY}/icons/uninstall.png"!'Delete Task/Reminder':3 --button="Edit a Task/Reminder"!"${DIRECTORY}/icons/edit.png"!'Edit a Task/Reminder':4 --list --column=Task/Reminder "${items[0]}" --column=Date "${items[1]}" button=$? #get exit code to determine which button was pressed.)"
+    if [ "$button" -eq 252 ];then
       exit 0
     elif [ "$button" -eq 4 ];then
       echo "User wants to edit: $OPTION"
